# Generated by Django 3.2.16 on 2023-11-29 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioCalistenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('musculos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatronMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('Ejercicios', models.ManyToManyField(to='navbar.EjercicioCalistenia')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ejerciciocalistenia',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navbar.patronmovimiento'),
        ),
    ]
