# Generated by Django 3.2.16 on 2023-12-23 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Traccion', 'Dominadas y FrontLvrs'), ('Empuje', "planchas y PushUp's"), ('Piernas', 'Piernitas'), ('Abdomen', 'Abdominales')], max_length=255, null=True)),
                ('url_video', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Básicos', 'entrenamiento de los básicos'), ('Traccion', 'Entrenamiento Enfocado en FrontLever o MuscleUp'), ('Empuje', "Entrenamiento enfocado en planchas y PushUp's"), ('FullBody', 'Entrenamiento de acodicionanmiento')], max_length=255, null=True)),
                ('level', models.CharField(blank=True, choices=[('Básico', 'solo entrenamiento de Fuerza, básicos'), ('Principiante', 'Principiante con bases sólidas'), ('Intermedio', 'Domina perfecto movimientos básicos'), ('Avanzado', 'Domina algunos élementos básicos de tensión'), ('Atleta', 'Domina elementos de tensión y está perfeccionando')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentario (little or no exercise)'), ('Poca_actividad', 'Ligeramente activo (light exercise/sports 1-3 days/week)'), ('Actividad_moderada', 'Moderadamente activo (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Muy activo (hard exercise/sports 6-7 days a week)')], max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True)),
                ('observations', models.CharField(blank=True, max_length=600, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.routine')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.userprofile')),
            ],
            options={
                'unique_together': {('user', 'routine', 'start_date')},
            },
        ),
    ]
