# Generated by Django 3.2.16 on 2024-01-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('class_hour', models.CharField(choices=[], max_length=5)),
                ('class_location', models.CharField(blank=True, choices=[('GYM Microcentro', 'Gimnasio especializado Microcentro'), ('GYM Belgrano', 'Gimnasio especializado Belgrano'), ('PRK Centenario', 'Parque Centenario'), ('PRK Chacabuco', 'Parque Chacabuco'), ('PRK Las Heras', 'Parque las Heras'), ('PRK Avellaneda', 'Parque Avellaneda'), ('PRK Los Andes', 'Parque los Andes'), ('PRK Irlanda', 'Plaza Irlanda')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.userprofile')),
            ],
        ),
    ]
