# Generated by Django 3.2.16 on 2023-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_alter_userprofile_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.CharField(blank=True, choices=[('Básicos', 'entrenamiento de los básicos'), ('Traccion', 'Entrenamiento Enfocado en FrontLever o MuscleUp'), ('Empuje', "Entrenamiento enfocado en planchas y PushUp's"), ('FullBody', 'Entrenamiento de acodicionanmiento')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='level',
            field=models.CharField(blank=True, choices=[('Básico', 'solo entrenamiento de Fuerza, básicos'), ('Principiante', 'Principiante con bases sólidas'), ('Intermedio', 'Domina perfecto movimientos básicos'), ('Avanzado', 'Domina algunos élementos básicos de tensión'), ('Atleta', 'Domina elementos de tensión y está perfeccionando')], max_length=50, null=True),
        ),
    ]
