# Generated by Django 3.2.16 on 2024-01-14 15:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_auto_20240114_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numero de Contacto'),
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
