# Generated by Django 3.2.16 on 2023-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='observations',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
