# Generated by Django 3.2.16 on 2023-12-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0011_alter_userprofile_observations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine',)},
        ),
    ]
