# Generated by Django 3.2.16 on 2023-12-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0014_alter_routineexercise_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine',)},
        ),
    ]
