# Generated by Django 3.2.16 on 2023-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0015_alter_routineexercise_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine_id',)},
        ),
    ]
