# Generated by Django 3.2.16 on 2023-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_auto_20231212_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('Traccion', 'Dominadas y FrontLvrs'), ('Empuje', "planchas y PushUp's"), ('Piernas', 'Piernitas'), ('Abdomen', 'Abdominales')], max_length=255, null=True),
        ),
    ]
